### ISSUE TITLE
Next release : 0.4.0

### ISSUE THREAD

**Issue by mpariente** [asteroid-team/asteroid#303]
- [ ] ~~Add compatibility tests for pretrained models (#294)~~ Follow up release
- [x] Fix DCCRN #276 
- [x] Jitability of DCCRN, DCUNet, complex_nn and TDCNpp

If we can merge #298 #302 and #257, it's also cool, but not required. 
After that, we'll need to upgrade pytorch-lightning.

**Comment by popcornell** [comment]
After this release we can break things and not be tied to be retro-compatible ?

**Comment by mpariente** [comment]
0.4.0 will break BC in few ways:
- `filters` is a method and not a property in `Filterbank`
- Some methods in `PITLossWrapper` return different type of indices (not used in our code base)
- Other ways in coming PRs.  

Those are very small BC break IMO. 

> After this release we can break things and not be tied to be retro-compatible ?

No, we'll try to be backwards compatible (BC) the most we can, always.
If we want to break BC completely, it'll be on asteroid 1.0.0 (exciting!). 

Are there things that would require to break BC currently? Is this related to [your comments](https://github.com/mpariente/asteroid/pull/306#issuecomment-721616859) in #306 ?

**Comment by popcornell** [comment]
Yeah I was thinking exactly that. The refactoring of masknn.

**Comment by mpariente** [comment]
Should we remove DCCRN fix and compatibility tests from the 0.4.0 release? 
I'd like to release quite soon so that we can work on 0.4.1 to upgrade lightning. 

I think both of these are assigned to you @jonashaag :wink:

**Comment by jonashaag** [comment]
I can put a DCCRN PR today, it only has be cleaned up. I don't know much about jitability though so not sure how long that will take. I can also work on #279 today

**Comment by mpariente** [comment]
Great thanks ! 

`script` doesn't allow function definition, so `on_reim` won't be scriptable, but probably traceable, but not even sure. I can do that part if you want.

**Comment by mpariente** [comment]
We're finally ready for 0.4.0 release, thanks a lot for your dedicated work !

**Comment by mpariente** [comment]
The docs has several empty sessions, I need to fix that.

**Comment by mpariente** [comment]
Released ! :rocket:
