### ISSUE TITLE
get the opposite estimate source with the original source

### ISSUE THREAD

**Issue by Sandydreamsmile** [asteroid-team/asteroid#372]
I was using the DPRNN model in my research to separate the mixture audio. After I trained the model with my audio set. I got the val_loss is -8.6 in SI-SDR. When I use the  inference scripts in the tutorial with the model to separate the mixture audio, I got two opposite estimated sources.
eg: est_1 is similar with s2, and est_2 is similar with s1.

My test scripts like below.

-----------------------------------
exp_dir = 'model'
model_path = os.path.join(exp_dir, 'best_model.pth')
model = DPRNNTasNet.from_pretrained(model_path)
model.cuda()
filename = './test_sample/audio.wav'
model.separate(filename)
-----------------------------------

But when I use the script "eval.py", I got the right sort sources. 
eg: est_1 is similar with s1, and est_2 is similar with s2.
I checked the script but I still don't know why I have this problem.
Could you help me with this ?

**Comment by mpariente** [comment]
The model is trained in a permutation invariant way, so this is to be expected. 
To reorder, we use `PITLossWrapper`, [see here](https://github.com/asteroid-team/asteroid/blob/master/egs/wham/ConvTasNet/eval.py#L70) with the `return_est=True` flag.

**Comment by Sandydreamsmile** [comment]
Thank you for your reply! I am a beginner in speech. 

You mean that actually sources order are opposite after processed by the model. But you set the parameter return_est=True in the training and validating process, then reorder the sources to the right order. Am I right?

**Comment by mpariente** [comment]
They are not always swapped, it's randomly determined by the network. And if we have the reference signals, you can use this function to reorder the estimates according to it.
