### ISSUE TITLE
Default Mask activation for Conv-TasNet

### ISSUE THREAD

**Issue by xixihahaggg** [asteroid-team/asteroid#373]
I read the paper of Astroid and it reported that Conv-TasNet built on Astroid outperform than the one reported in oringinal paper. And I found that the default mask activiation function in Astroid is relu where the oringnal one use sigmoid. So why use relu in default setting? Which activation function you use for the results that showed on paper. I'm wondering whether it is affected by the activation function.

**Comment by mpariente** [comment]
The results in the paper are obtained with the pretrained model here: https://zenodo.org/record/3862942 with relu mask activation indeed. 
I'm not sure that this brings the largest part of the performance boost, but you can try with the sigmoid mask activation to check, feel free to share.

**Comment by prashant45** [comment]
I noticed that the architecture has a multiplication of inputs and mask estimates. Is it implemented in your version, I failed to find this operation before the decoder? 
If so, can you direct me to the code line.

**Comment by mpariente** [comment]
Have a look at the base class `BaseEncoderDedoder` in one of the hook methods.

**Comment by prashant45** [comment]
Thanks for the quick response. 
Another question in regards to relevance to the paper. I see the LibriMix/ConvTasNet defaults settings does not use `relu` activation after `Encoder`. Any particular reason to use non-negative TF representation of the input, in contrast to what is mentioned in the paper ?

**Comment by mpariente** [comment]
Linear activation yields the best result, even in the original paper. 
![image](https://user-images.githubusercontent.com/18496796/106158643-3f450f80-6184-11eb-9b9e-948509d2477a.png)

**Comment by prashant45** [comment]
hey, sorry for that. Missed the table in the paper. 
Btw, good clean repo.
