### ISSUE TITLE
Restrict setup.py to python >=3.6 and <3.9 (avoid error when current python env uses 3.9 version)

### ISSUE THREAD

**Issue by tux-coder** [asteroid-team/asteroid#376]
### Before reporting a bug:
First, please search [previous issues](https://github.com/asteroid-team/asteroid/issues)
and [the FAQ](https://asteroid-team.github.io/asteroid/faq.html) and be sure this hasn't
been answered elsewhere.

## 🐛 Bug

On rolling release distros (archlinux, gentoo etc...) the current python version provided is 3.9 by default.
And the setup.py file of asteroid doesn't restrict python to version below to 3.9, on line 18 we can read this

```
 python_requires=">=3.6",
```

this leads to a crash of asteroid during its installation with pip procedure, on a virtual environment where the last release version of python is used (3.9.0),
commands like "pip install asteroid", or "pip install -e ." on such environment will lead to this error message : 

```
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.



    ERROR: Command errored out with exit status 1:
     command: /tmp/env_asteroid/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cpjnblv8/pesq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cpjnblv8/pesq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8vidcl9n
         cwd: /tmp/pip-install-cpjnblv8/pesq/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cpjnblv8/pesq/setup.py", line 4, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
```

### To Reproduce

Steps to reproduce the behavior (code sample and stack trace):

- Use a linux distro where python 3.9 is installed by default (archlinux, gentoo)

- create and activate a virtual environment with python 3.9 inside (this environment should be new, no dependencies already installed like pytorch or numpy)

```
virtualenv3 /tmp/env_asteroid
```
or with conda : 
```
conda create -n myenv python=3.9
```

- Install pytorch by using pip commands, as a beginner would do if he reads the tutorial : 
```
pip install asteroid
```
or from the source code : 
```
pip install -e .
```
Result is crash of pytorch during installation : 
```
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

    ERROR: Command errored out with exit status 1:
     command: /tmp/env_asteroid/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cpjnblv8/pesq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cpjnblv8/pesq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8vidcl9n
         cwd: /tmp/pip-install-cpjnblv8/pesq/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cpjnblv8/pesq/setup.py", line 4, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
```
It's due to a lack of restriction for maximum python version allowed in setup.py (shoud be ">=3.6 and <3.9"), and also because pytorch is not yet compatible with python 3.9.

Solution is simply to update setup.py with a restriction on maximum version allowed of python (<3.9) : 

```
python_requires=">=3.6, <3.9",
```

### Expected behavior

Pip installation should finish without errors,
or pip should refuse the installation if setup.py would have a restriction to python version >=3.6 and <3.9

### Environment
Archlinux, where python 3.9 is by default the current release version
https://www.archlinux.org/packages/extra/x86_64/python/

#### Package versions
python 3.9
last version of asteroid (but can not be installed as python version is 3.9)

**Comment by mpariente** [comment]
Thanks for the detailed report. 

Mind submitting a PR to fix this?

**Comment by tux-coder** [comment]
Yes, I will do a PR.

**Comment by jonashaag** [comment]
Hey, thanks for the detailed report. However I think your conclusions aren't correct.

1) I think the error you are seeing is https://github.com/ludlows/python-pesq/pull/9
2) If I'm not mistaken there isn't any code in Asteroid that requires Python <= 3.9, except for the dependencies. In this case, any dependency resolver will restrict Python to <= 3.9 anyways

**Comment by tux-coder** [comment]
Thanks Jonashaag,

yes you are right, if I install numpy and cython before asteroid then pip installation can go further, then it stops : 

```
ERROR: Could not find a version that satisfies the requirement torchaudio (from torch-stoi->asteroid==0.4.0) (from versions: none)
ERROR: No matching distribution found for torchaudio (from torch-stoi->asteroid==0.4.0)
```
I will try the commit you propose : 
https://github.com/ludlows/python-pesq/commit/fbd48e08b6a9620fac7b720eb70c8759ec9cacf6

**Comment by jonashaag** [comment]
If we haven't documented it already, maybe a better "fix" for the problem would be to simply add a note in the installation instructions that currently some (which?) of the dependencies don't support Python version > X

**Comment by tux-coder** [comment]
I think it's pytorch that is not compatible with python 3.9, see this bugreport : 
https://github.com/pytorch/pytorch/issues/47116

I tried to install pytorch on empty python environment 3.9 (on archlinux), and I get the same error as described in the bugreport, when using pip command and when default python version is 3.9 :
 
```
ModuleNotFoundError: No module named 'tools.nnwrap'
```
Workaround is to stay with python 3.6 - 3.8,  and indeed to add a note on installation instructions about python 3.9, currently the instructions don't say explicitly that python 3.9 will cause problems (if you go straight to installation section and want to use the pip method) : 
https://github.com/asteroid-team/asteroid#installation

**Comment by jonashaag** [comment]
PyTorch supports 3.9 now, closing this.
