### ISSUE TITLE
Wrong sample rate on Wham-ConvTasNet recipe when training a 16000 Hz model

### ISSUE THREAD

**Issue by Potomac** [asteroid-team/asteroid#392]
I detected a bug in Wham/ConvTasNet recipe, located in the file train.py :

when training a model with a sample rate of 16000 Hz then the model (best_model.pth file) generated (by run.sh)  is registered with a sample rate of 8000 Hz instead of 16000 Hz,

it's because the sample rate value is not passed when ConvTasNet class is instancied at line 60 of train.py file : 

```
model = ConvTasNet(**conf["filterbank"], **conf["masknet"])
```
a solution is to add the sample rate value (in order to avoid the default value 8000 Hz) : 

```
 model = ConvTasNet(**conf["filterbank"], **conf["masknet"], sample_rate=conf["data"]["sample_rate"])
```

https://github.com/asteroid-team/asteroid/blob/master/egs/wham/ConvTasNet/train.py

**Comment by mpariente** [comment]
This is correct, thanks for pointing it out! Could you submit a PR to fix
this please?
Thanks
