### ISSUE TITLE
MULCATDPRNN?

### ISSUE THREAD

**Issue by Onlytwow** [asteroid-team/asteroid#396]
hello

I am coding the MULCATDPRNN, while its performance is not so good. I remember that there was MULCATDPRNN in your README. I think I can compare my code with yours, so that I can find out the problems. But it disappeared in your list. So I want to konw why you remove it from the list ? 

Look forward to your reply

**Comment by popcornell** [comment]
Hi, 

As far as i am aware we never had MulCat DPRNN  from https://arxiv.org/pdf/2003.01531.pdf. 
We have however standard DPRNN and it is pretty well tested. 
How is performance ? what do you mean not so good ? worse than plain DPRNN ?

**Comment by Onlytwow** [comment]
> Hi,
> 
> As far as i am aware we never had MulCat DPRNN from https://arxiv.org/pdf/2003.01531.pdf.
> We have however standard DPRNN and it is pretty well tested.
> How is performance ? what do you mean not so good ? worse than plain DPRNN ?

Maybe my memory is wrong. The best performance I got is worse than the plain DPRNN. I will check it out and train it again. Thanks for you reply.

**Comment by mpariente** [comment]
Closing now, but we plan to add it. 
See #412
