### ISSUE TITLE
Proper STFT configuration for DCUNet

### ISSUE THREAD

**Issue by jonashaag** [asteroid-team/asteroid#400]
## 🐛 Bug

For DCUNet, we currently use a 512/256 STFT. In the paper they use 1024/256. My own experiments show a large drop of performance for 512 FFT, and a large drop for hop >= 1/2 FFT. I don't see a performance increase with 2048/512.

I suggest to change the default to 1024/256.

Note that my tests were done with `torch_stft_fb`.

**Comment by mpariente** [comment]
Yes, let's use the defaults as in the paper, sure.

**Comment by mpariente** [comment]
Fixed by #406
