### ISSUE TITLE
Allow https:// URL for Hugging Face download

### ISSUE THREAD

**Issue by jonashaag** [asteroid-team/asteroid#401]
## 🚀 Feature

Currently when you just copy and paste a HF hosted model URL from the browser (eg. https://huggingface.co/mhu-coder/ConvTasNet_Libri1Mix_enhsingle) to `asteroid-infer`, you this error:

```
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    model = BaseModel.from_pretrained(model_id)
  File "/usr/local/lib/python3.8/dist-packages/asteroid/models/base_models.py", line 122, in from_pretrained
    conf = torch.load(cached_model, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

Probably because it downloads the page as HTML and then tries to parse that as pickle file.

### What you'd like

Recognise HF urls like https://huggingface.co/mhu-coder/ConvTasNet_Libri1Mix_enhsingle and have them behave the same as without the https://huggingface.co/ prefix

cc @julien-c

**Comment by mpariente** [comment]
That would be great indeed ! 
Do you feel like having a look?

**Comment by jonashaag** [comment]
@julien-c what are your thoughts on adding support for `https://huggingface.co/user/model` to `hf_hub_url` in the Hub library?

**Comment by mpariente** [comment]
Let's first migrate to the new library https://github.com/huggingface/huggingface_hub, and then we'll have a look at how we can do that.

**Comment by jonashaag** [comment]
I can also submit a PR to the integration library if you agree with that feature
