### ISSUE TITLE
Large-DCUNet-20 decoder misconfiguration 

### ISSUE THREAD

**Issue by JorisCos** [asteroid-team/asteroid#403]
## 🐛 Bug
The configuration provided in `_dcunet_architectures.py` for `Large-DCUNet-20` will lead to an error when decoding.
The decoder isn't set to `auto` not sure why.
Anyway, I think (need to be checked) the right configuration is 
```Python 
       # Decoders:
        # (in_chan, out_chan, kernel_size, stride, padding, output_padding)
        (
            (128, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (7, 5), (2, 1), "auto", (0, 0)),
            (180, 45, (7, 5), (2, 2), "auto", (0, 0)),
            (90, 45, (1, 7), (1, 1), "auto", (0, 0)),
            ( 90,  1, (7, 1), (1, 1), "auto", (0, 0)),
```

**Comment by jonashaag** [comment]
Yeah I realised that as well, there is a typo in the last line. The correct decoders list is

``py
            (128, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 1), "auto", (0, 0)),
            (180, 90, (5, 3), (2, 2), "auto", (0, 0)),
            (180, 90, (7, 5), (2, 1), "auto", (0, 0)),
            (180, 90, (7, 5), (2, 2), "auto", (0, 0)),
            (135, 90, (1, 7), (1, 1), "auto", (0, 0)),
            (135,  1, (7, 1), (1, 1), "auto", (0, 0)),
```

<img width="558" alt="Screenshot 2021-01-04 at 16 03 33" src="https://user-images.githubusercontent.com/175722/103548749-89e5ab80-4ea6-11eb-9016-5131a8fdec8f.png">

Maybe "auto" actually does the right thing and for some reason I thought it doesn't?

**Comment by JorisCos** [comment]
Ok I missed this figure. Actually "auto" does what I suggested so no we should definitely fix with your config
