### ISSUE TITLE
Hooks: Document passing System.on_xxx to model.on_xxx

### ISSUE THREAD

**Issue by jonashaag** [asteroid-team/asteroid#411]
## 📚 Documentation

`System` defines a bunch of placeholder hooks like `on_batch_start`, but doesn't pass them to the wrapped model or datasets. This was surprising to me because I expected `System` to be a transparent wrapped around `model`. I don't think we should change it to automatically forward those hooks to the model etc., but I think we should document it in `System` that if you want those hooks to reach your model instance, you'll have to do it yourself.

Plus, what do you think about removing the empty `on_xxx` methods from `System`? They aren't doing anything and the fact that only an arbitrary subset of possible hooks is defined there may be confusing to people (me).

**Comment by mpariente** [comment]
Just to be sure I understand, you wrote the `hooks` in your model and expected them to be called from the `System`'s hooks? 
The forwarding is pretty simple, we could do it, IDK. 

> what do you think about removing the empty `on_xxx` methods from `System`?

Yes, it makes sense. We just link to the lightning docs about hooks.

**Comment by jonashaag** [comment]
> Just to be sure I understand, you wrote the `hooks` in your model and expected them to be called from the `System`'s hooks?

Yes, or to be exact I forgot that there is a `System` "between" PL and my model.

For auto-forwarding, we could implement it using `__getattr__` or model introspection. `System` could forward to the model automatically, or raise a warning that it doesn't do automatic forwarding.

**Comment by mpariente** [comment]
If we choose to forward it, what happens if both the model and a subclass of `System` implement hooks? Do we forward everything or just the known hooks from PL? 
What about data modules? 

It's easier just not to forward IMO. Hooks might involve something else than the model most of the time, so it makes sense to keep them in `System`. 

> For auto-forwarding, we could implement it using `__getattr__`.

That's what I had in mind for the implementation.

**Comment by jonashaag** [comment]
Agreed, let's start with removing the empty `on_xxx` methods and adding a note to the docs.
