### ISSUE TITLE
Switch from julius to torchaudio?

### ISSUE THREAD

**Issue by jonashaag** [asteroid-team/asteroid#419]
julius' resample implementation has been merged into torchaudio: https://github.com/pytorch/audio/issues/1057

Shall we switch to that as soon as the new torchaudio is released? (Would probably mean that we don't support earlier versions of PyTorch anymore though, because of torchaudio->PyTorch dependency?)

**Comment by mpariente** [comment]
> Would probably mean that we don't support earlier versions of PyTorch anymore though, because of torchaudio->PyTorch dependency?

Yes, what's your take on that?

**Comment by jonashaag** [comment]
I think it’s not worth it dropping 1.6 support just for this one fewer dependency.

**Comment by mpariente** [comment]
I'd agree with that. 
But when will we move then? :smile:

**Comment by jonashaag** [comment]
Let's discuss it again in 2023 :-D

**Comment by mpariente** [comment]
Let's see the future releases of PyTorch. Maybe we'll switch to new ones only because of complex support? 

I'll keep in mind but I'll close now.

**Comment by anjali411** [comment]
@mpariente torchaudio 0.9 release supports native complex types now! (https://github.com/pytorch/audio/releases)

**Comment by mpariente** [comment]
Thanks @anjali411 :+1:
