### ISSUE TITLE
[Design] Multichannel model support

### ISSUE THREAD

**Issue by mpariente** [asteroid-team/asteroid#420]
### What we want 
- Suport in `BaseModel` for save/load/share
- Support in `separate` for the inference API + CLI.

### Proposed design
- Add `channels` (or `n_chan`, `n_channels`?) to `BaseModel`.
- Add `channels` to `separate` and `Separable`. 

Is there anywhere else where we need to change it? 

### Questions: 
- Should `channels` be handle the same way as `sample_rate` (hidden attribute + property)? 
- How should we handle models that support several number of channels? Using `List` or `None`? 
- Should we raise errors in `separate` if the number of input channels is different than the expected number? Or remove the channels? Or apply the network to each channel? etc...

**Comment by popcornell** [comment]
Maybe mic_channels is better ? 

> 
> Should channels be handle the same way as sample_rate (hidden attribute + property)?
> How should we handle models that support several number of channels? Using List or None?

FasNet TAC can handle an arbitrary amount of channels actually.

**Comment by mpariente** [comment]
> What do you mean by list ? empty list ?

If a method works with 1, 2 or 3 mics but not more. But actually, in #427, I propose either `int` or `None`. If `None`, we don't check anything. 

> BTW now is there a way to apply easily a single-channel system to multiple channel audio ?

No, there is not. 
Do you think we should have it in the CLI? 
Because otherwise the user can loop over the channels, I guess it's pretty simple. 
```python
torch.stack([model.separate(w[None]) for w in wav]) 
```


> Maybe mic_channels is better ?

I opted for `n_channels` in the PR but we can discuss it. 

Thanks for the feedback

**Comment by jonashaag** [comment]
> If a method works with 1, 2 or 3 mics but not more. But actually, in #427, I propose either `int` or `None`. If `None`, we don't check anything.

Yes, let's keep it simple for now, as you suggested.

> > BTW now is there a way to apply easily a single-channel system to multiple channel audio ?
> 
> No, there is not.
> Do you think we should have it in the CLI?

I think this could be useful and easy to implement. We can start by supporting only input channels >= 1, and model channels = 1, and add a CLI flag that applies to model to all the channels separately.

> > Maybe mic_channels is better ?
> 
> I opted for `n_channels` in the PR but we can discuss it.

I have seen people confused about "channels" and "sources" etc multiple times. I think anyone not familiar with source separation is quick to think of "source" = "my audio files". How about naming the both simply "input_channels" and "output_channels"?

**Comment by mpariente** [comment]
> We can start by supporting only input channels >= 1, and model channels = 1, and add a CLI flag that applies to model to all the channels separately.

And how do you generalize that to multichannel models? 


> I have seen people confused about "channels" and "sources" etc multiple times. I think anyone not familiar with source separation is quick to think of "source" = "my audio files". How about naming the both simply "input_channels" and "output_channels"?

I wouldn't call them input_channels and output_channels. We should rather use source separation vocabulary, and document it well. 

Maybe `n_mics` would be better in the case that `n_channels` is not clear enough.

**Comment by jonashaag** [comment]
`n_mics` is very specific though, and might be misleading in case of mono/stereo (ok well technically a stereo mic is two mics but not sure that's a useful way to think about it...)

**Comment by popcornell** [comment]
Maybe i am late but what about `signals` ? or `n_sig`

**Comment by iver56** [comment]
Just putting this here in case it's useful:

In [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations) multichannel audio tensors are 3-dimensional with axes like `[batch_size, num_channels, num_samples]`

This was a result of discussions in the asteroid slack and on Github

**Comment by mpariente** [comment]
Thanks @iver56!
I remember this conversation, and I still think channels first make more sense with PyTorch. 



> Maybe i am late but what about `signals` ? or `n_sig`

Actually, we (I) merged with `n_channels` but changed it to `in_channels` to be consistent with PyTorch's conv ops.

**Comment by mpariente** [comment]
Solved in #427
