### ISSUE TITLE
Input tensors to DPRNN and DPTransformer

### ISSUE THREAD

**Issue by ntyoshi** [asteroid-team/asteroid#436]
I'm trying to understand asteroid project more and I have a question about input tensors to DPRNN and DPTransformer.

I added following codes at the beginning of forward method of DPRNN and DPTransformer.
```       
 x = mixture_w
 x[x >= 0] = 0
 x[x <  0] = 1
 print(torch.sum(x))
```
I wanted to count negative values in their input tensors.
In the case of DPTransformer, the results were always 0 but those of DPRNN weren't same (I got 80, 3772, 4124 ...).
As far as I read your code, the preprocesses of DPRNN and DPTNet are same but why is this happened? 
Sorry for a basic question but I'll appreciate if you help me.
Thank you!

**Comment by mpariente** [comment]
There is an activation function in the encoder (check `BaseEncoderMaskerDecoder`), probably the default in `DPTNet` is a ReLU. I'll let you check and confirm that.

**Comment by ntyoshi** [comment]
Oh I missed that! Thank you for helping my question.
