### ISSUE TITLE
Reshaping issue in Looking-to-Listen model.py

### ISSUE THREAD

**Issue by vskadandale** [asteroid-team/asteroid#438]
It seems the reshaping operation [here](https://github.com/asteroid-team/asteroid/blob/master/egs/avspeech/looking-to-listen/model.py#L494) is done incorrectly. 
Here, we are reshaping `(N, 298, 2x257xself.num_person)` into `(N, 2, 298, 257, self.num_person)`. 
Instead of `view(N, 2, 298, 257, self.num_person)`, it will be more appropriate to do 
`view(N, 298, 2, 257, self.num_person).transpose(1, 2)`.

**Comment by mpariente** [comment]
Feel free to send a PR, or @vitrioil :smiley:

**Comment by mpariente** [comment]
Fixed in #441
