### ISSUE TITLE
Model parameters for DPTNet

### ISSUE THREAD

**Issue by xixihahaggg** [asteroid-team/asteroid#445]
I was wondering about the model parameters for DPTnet. As reported in the paper, a 6 layers DPTNet should only contain 2.69M parameters. But in my experiment setup, a 6 layers DPTNet has 8.5M parameters which is much larger than primal one. I'm not sure what's the difference in the model implementation.

**Comment by mpariente** [comment]
@popcornell do you have an idea about this?

**Comment by popcornell** [comment]
The default for `ff_hid_size` should be 128 instead of 256. With that we have 2.8M, 0.1 M is due to the fact they do not biases in some layers.

**Comment by xixihahaggg** [comment]
Thank you for the clarification!
