### ISSUE TITLE
How to define DCCRN's params precision ?

### ISSUE THREAD

**Issue by realkris** [asteroid-team/asteroid#447]
This project is really helpfull for noobs like me !
I want to make a DCCRN model(on DNS-Challenge official dataset) for class project as the noise cancellation module.

The problem is that the model is so big that it can not run on my P2000(with 5GB graphic memory), so I reduced the batch size to 1, but it still can not run. So I'm looking for methods to reduce the memory cost...
And one of them is to reduce the precision of  params, maybe from float32 to float16? but I don't know where I can do this...
also if there's other ways to reduce the memory cost, please help...

My English is not good, maybe I missed something? Thank you for your help!

**Comment by mpariente** [comment]
Maybe reduce the length of each example?

Or reduce the hidden sizes in the architecture?

**Comment by realkris** [comment]
Thanks for your reply.
Also I followed the guide in https://pytorch-lightning.readthedocs.io/en/stable/advanced/amp.html. if you have the same problem as me. this issue is closing.
