### ISSUE TITLE
dns_challenge recipe dataloader issue

### ISSUE THREAD

**Issue by raikarsagar** [asteroid-team/asteroid#462]
Hi, I am getting this error when running the baseline recipe
File "train.py", line 119, in <module>
    main(arg_dic)
  File "train.py", line 24, in main
    total_set = DNSDataset(conf["data"]["json_dir"])
TypeError: __init__() missing 4 required positional arguments: 'task', 'sample_rate', 'n_src', and 'segment'

**Comment by mpariente** [comment]
It seems you modified the dataset init right? 

In this case I'm closing.
