### ISSUE TITLE
The results of Encoder(STFTFB) and torch.stft are huge different

### ISSUE THREAD

**Issue by yangliuav** [asteroid-team/asteroid#472]
Hi, I current use asteroid 0.4.4, asteroid-filterbanks 0.3.2 and torch 1.8.1. I find the STFTFB and torch.stft's output are different. 

    ref = torch.range(1, 16000)
    test = torch.stft(ref, n_fft= 320)
    test = torch.istft(test, n_fft= 320)
    result0 = torch.sum((ref - test) ** 2) # tensor(1.0459e-08)
    f, t, Zxx = signal.stft(ref, fs=16000)
    _, test2 = signal.istft(Zxx, 16000)
    result1 = torch.sum((ref - test2) ** 2) # tensor(0.0085)
    encoder = Encoder(STFTFB(kernel_size=320, n_filters=320, stride=160, sample_rate = 16000))
    decoder = Decoder(STFTFB(kernel_size=320, n_filters=320, stride=160, sample_rate = 16000))
    wav = decoder(encoder(ref))
    result2 = torch.sum((ref - wav) ** 2) # tensor(1.5164e+10)
   
As shown, after torch.stft and torch.istft, the error is low as 1.0459e-08. However, for asteroid STFT, the error would be 1.5164e+10. Maybe my usage is not correct. Please help to point out it.

**Comment by mpariente** [comment]
If you plot them, you see this: 
![image](https://user-images.githubusercontent.com/18496796/113340392-20056280-932c-11eb-9ec1-f8d77bf312a7.png)
The black is `wav`. What you see is the last hanning window. We don't divide by the squared overlap added window, because we believe it's a bad habit that introduce artifacts and makes real-time applications harder. 

So, in my eyes, the results are exactly as expected. 

Note, rather use `torch.randn(1, 16000)` for testing things, `torch.range` has weird statistics.

**Comment by mpariente** [comment]
I'll close because I don't consider this to be an issue.

**Comment by yangliuav** [comment]
Thank you for your kindly reply. I am agree to use torch range to test it. However, if we use torch.randn, the result is similar.

ef = torch.randn(1, 16000)
    test = torch.stft(ref,  n_fft = 320)
    test = torch.istft(test,  n_fft = 320)
    result0 = torch.sum((ref - test) ** 2) # tensor(1.2692e-10)

    f, t, Zxx = signal.stft(ref, fs=16000)
    _, test2 = signal.istft(Zxx, 16000)
    result1 = torch.sum((ref - test2) ** 2) # tensor(1.4588e-10)
    
    encoder = Encoder(STFTFB(kernel_size=320, n_filters=320))
    decoder = Decoder(STFTFB(kernel_size=320, n_filters=320))
    wav = decoder(encoder(ref))
    result2 = torch.sum((ref - wav) ** 2) # tensor(131.4723)

It is still much different. Thank you.

**Comment by mpariente** [comment]
Did you understand what I mentionned before? It's because of the first and last frames, and this is expected. 
Try to compute the error from 320 to -320 and you'll have perfect reconstruction. 
Or plot it and you will see.

**Comment by yangliuav** [comment]
I get it. Thank you very much for your help.
