### ISSUE TITLE
NCCL error

### ISSUE THREAD

**Issue by Wzw666888** [asteroid-team/asteroid#473]
Hello, dear developer:
        Thank you for your contribution to speech separation.Recently,however,I ran into a problem this framework. The description of the problem is NCCL error that ProcessGroupNCCL.cpp:784，unhandled system error. I searched a lot of information but couldn't solve this problem. But I think I may be a single host with multiple GPUs not set up correctly. Please give me a correct guide, thank you.
![error](https://user-images.githubusercontent.com/82068553/113951576-63893080-9846-11eb-91ac-37239a9accab.png)

**Comment by mpariente** [comment]
Sorry, I have never has such problems and probably don't know how to solve
it.

Good luck

**Comment by mpariente** [comment]
Closing.
