### ISSUE TITLE
catalyst.dl.core

### ISSUE THREAD

**Issue by MordehayM** [asteroid-team/asteroid#500]
The package isn't found at this line:
https://github.com/asteroid-team/asteroid/blob/8a1841611704ce5f55728e92bf273a2451258f8c/egs/avspeech/looking-to-listen/train/callbacks.py#L5
Tried to reinstall..didn't work.

**Comment by mpariente** [comment]
Catalyst probably changed version since then. 
You could either: 
1. Update the code
2. Try to ping the author of the code: @vitrioil are you here? 
3. Find the version with which the recipe was written

**Comment by vitrioil** [comment]
@MordehayM  which catalyst version are you using?
Can you try creating a virtualenv?
```bash
python3 -m venv env
source env/bin/activate
pip install --upgrade pip
pip install local/requirements.txt
```
I will have to check why it is not working for the future version
