### ISSUE TITLE
Sepformer Implementation

### ISSUE THREAD

**Issue by xixihahaggg** [asteroid-team/asteroid#510]
I've implemented the Sepformer as described in https://arxiv.org/abs/2010.13154. However, the performance is much worse has a much slower convergence speed than the RNN-based model. Do you guys have any ideas or experience of training Sepformer? Thank you!

**Comment by mpariente** [comment]
@popcornell is one of the authors in the paper, I'm sure he could answer that!

**Comment by popcornell** [comment]
Are you sure there is not something off with your implementation ? Have you tried the official one ? You can wrap it pretty easily and use it in Asteroid right away.

**Comment by xixihahaggg** [comment]
Thank you for your advice. I will try the official one using Asteroid and give the feedback.
