### ISSUE TITLE
Use librosa.resample(res_type="sox")

### ISSUE THREAD

**Issue by jonashaag** [asteroid-team/asteroid#522]
librosa got support for https://github.com/dofuuz/python-soxr based resampling, see https://librosa.org/doc/latest/generated/librosa.resample.html#librosa.resample. So we can drop our custom fast-resampling code here:
https://github.com/asteroid-team/asteroid/blob/b49069f3e6572960c11c0e60d537ffb959c93ea2/asteroid/separate.py#L182-L195

**Comment by mpariente** [comment]
Did you benchmark it? 
Julius is much lighter than librosa as a dependency. 
Do you think we should add librosa again?

**Comment by jonashaag** [comment]
Ooh, you are right, we have librosa as an optional dependency. I forgot about that. Let's keep as is or maybe change to native Torchaudio resampling (which is the same as julius in latest release)

**Comment by faroit** [comment]
@jonashaag @mpariente i would also vote for keeping julius - or any other kind of torch native code. It may not be the fasted solution now, but it sure will get faster over time as pytorch improves on these ops
