### ISSUE TITLE
No module named 'asteroid.filterbanks'

### ISSUE THREAD

**Issue by hihunjin** [asteroid-team/asteroid#525]
## 🐛 Bug

```python
from asteroid.filterbanks import STFTFB, Encoder, Decoder
```

This gets me an error 
```sh
ModuleNotFoundError: No module named 'asteroid.filterbanks'
```

When I run [this notebook, 01-APIOverview.ipynb](https://github.com/asteroid-team/asteroid/blob/master/notebooks/01_APIOverview.ipynb).

### To Reproduce
```python
from asteroid.filterbanks import STFTFB, Encoder, Decoder
```
#### Package versions

Run `asteroid-versions` and paste the output here:

```
Asteroid            0.5.2dev
PyTorch             1.9.0+cu102
PyTorch-Lightning   1.3.8
```

#### Additional info

#346
This issue is related to the PR : [src] Transition to asteroid_filterbanks(#346)

**Comment by mpariente** [comment]
Yes, this should be `asteroid_filterbanks` indeed. 
Do you feel like submitting a PR please?

**Comment by hihunjin** [comment]
@mpariente Yes. I opened this issue to do PR.
