### ISSUE TITLE
MixIT seems to hard to train

### ISSUE THREAD

**Issue by jyhan03** [asteroid-team/asteroid#531]
### Before asking:
1. search the [issues](https://github.com/asteroid-team/asteroid/issues).
2. search the [discussions](https://github.com/asteroid-team/asteroid/discussions)
3. search the docs.

Open a question on the [Discussions](https://github.com/asteroid-team/asteroid/discussions/new)

Hello, I run the example of MixIT, but I find that the validation loss only drops to -2.7 dB (SISNR) after 76 epoch. 
I didn't modify any configurations other than changing the dataset to whamr clean. However, It seems the training process is abnormal. I guess it's hard to train it. 

The validation loss after 76 epoch is shown as follows:
![未命名1627571890](https://user-images.githubusercontent.com/48471602/127518822-421ffa2d-216b-49a1-9a10-2a50df1c557d.png)

**Comment by mpariente** [comment]
Thanks for raising the issue. I'll start investigating MixIT behavior in September and find out if anything is wrong with it. We get a lot of mixed feedback on the current implementation.

**Comment by jyhan03** [comment]
Thanks. Looking forward to a good solution~

**Comment by mpariente** [comment]
@jyhan03 I know I'm late, but have you found a solution for your problem in the end ?

**Comment by jyhan03** [comment]
> @jyhan03 I know I'm late, but have you found a solution for your problem in the end ?

Hi, I didn't follow it in the end. I also asked someone for their MixIT solution, strangely, the code worked still badly on my side. 

How about you? Do you have any solutions or it's just my problem?

**Comment by mpariente** [comment]
No, I didn't find a solution yet, but I just started;

**Comment by jyhan03** [comment]
> No, I didn't find a solution yet, but I just started;

Looking forward to a good solution.
