### ISSUE TITLE
DPRNN model structure

### ISSUE THREAD

**Issue by JusperLee** [asteroid-team/asteroid#532]
### Before asking:
1. search the [issues](https://github.com/asteroid-team/asteroid/issues).
2. search the [discussions](https://github.com/asteroid-team/asteroid/discussions)
3. search the docs.

Open a question on the [Discussions](https://github.com/asteroid-team/asteroid/discussions/new)

I observed that the results of dprnn in asteroid are better than the results inside the paper. But I think this is not in accordance with the structure of dprnn in the original paper, and also not in accordance with the setting of the output-layer in FasNet. After using gate cnn in the output-layer, it should be used as output directly, instead of inputting output-layer output into relu as final output.

**Comment by mpariente** [comment]
Why did you close the issue?

Le mar. 3 août 2021 à 09:48, Kai Li (李凯) ***@***.***> a
écrit :

**Comment by mpariente** [comment]
It probably affects the performance. We made some experiments with Samu before choosing one architecture and this was also close to the code in Yi's repo, but I don't remember all the details about why etc..

**Comment by JusperLee** [comment]
https://github.com/asteroid-team/asteroid/blob/98d1241af488692e62283ee31a9498a1f69c4199/asteroid/masknn/recurrent.py#L472-L475

These few lines of code are only needed for DPRNN for relu. For FasNet only gate-output layer is required.
