### ISSUE TITLE
missing asr model reference

### ISSUE THREAD

**Issue by moonlightSong** [asteroid-team/asteroid#542]
https://github.com/asteroid-team/asteroid/blob/64e10e9de840ada77719ff4fa280be42a19aa51c/egs/librimix/DPTNet/eval.py#L52

Does anyone know any reference/paper about technical details of this asr model? There is only a training config .yaml online.

**Comment by mpariente** [comment]
Nope, sorry. I don't think there is a paper with all the ESPNet models.
