### ISSUE TITLE
Dependency mismatch

### ISSUE THREAD

**Issue by winlaic** [asteroid-team/asteroid#550]
While I am installing asteroid v0.4.4, it will unfailingly force me to reinstall a higher version of pytorch, but v0.4.4 just need pytorch>=1.3. It is hard for me to update CUDA version so I have to use pytorch<=1.7.1 since I have no root. I found that this bug is occurred due to asteroid-filterbanks' update. v0.4.4 only specified an asteroid-filterbanks higher than 0.2, which will let pip choose a newest version of asteroid-filterbanks that requires pytorch>=1.8.

**Comment by jonashaag** [comment]
Did you try 0.4.5?

**Comment by winlaic** [comment]
No, because I'm installing [s3prl](https://github.com/s3prl/s3prl), which specified asteroid's version just to 0.4.4. I don't know what will happen if I force to change the version to 0.4.5. Actually I've overcome this problem by manually install asteroid forcing not install dependencies and install dependencies one by one. Maybe the requirements file in 0.4.4 needs to be modified to let pip choose a lower version of asteroid-filterbanks.

**Comment by jonashaag** [comment]
Then `s3prl` needs to update their dependencies.

**Comment by mpariente** [comment]
Closing now. Feel free to reopen if it's still an issue.
