### ISSUE TITLE
SI-SDRi is greater than SDRi in experiment resutls

### ISSUE THREAD

**Issue by xixihahaggg** [asteroid-team/asteroid#551]
I found something weird in my experiment results for LibriMix. In almost every speech separation paper, they reported SDRi greater than SI-SDRi. However, according to my experiment results, the SI-SDRi is 1 dB greater than SDRi, did anyone have any insight about this?

**Comment by mpariente** [comment]
Oh, that's interesting. 
- Which implementations do you use? Specifically for SI-SDR
-Are your signals zero mean?

**Comment by xixihahaggg** [comment]
I used the get_metrics defined in asteroid.metrics,  so I think the implementation is consistent. I also track WER of separated speech. Here I report two results:
1. SI-SDRi: **16.32**, SDRi:15.47. WER: **0.332**
2. SI-SDRi: 15.57, SDRi:**16.02**. WER: 0.344
I observed that WER is consistent with SI-SDRi, not SDRi (SI-SDRi is higher, WER is lower). So I think SI-SDRi might be more appropriate to evaluate the separation quality. But I still confuse as that why the results have higher SI-SDRi but with a lower SDRi.

**Comment by mpariente** [comment]
> So I think SI-SDRi might be more appropriate to evaluate the separation quality

Probably wouldn't jump to this conclusion, though.

**Comment by xixihahaggg** [comment]
Yeah, I will keep track of this problem, only two experiments can't draw this conclusion.

**Comment by jvel07** [comment]
> I used the get_metrics defined in asteroid.metrics, so I think the implementation is consistent. I also track WER of separated speech. Here I report two results:
> 
>     1. SI-SDRi: **16.32**, SDRi:15.47. WER: **0.332**
> 
>     2. SI-SDRi: 15.57, SDRi:**16.02**. WER: 0.344
>        I observed that WER is consistent with SI-SDRi, not SDRi (SI-SDRi is higher, WER is lower). So I think SI-SDRi might be more appropriate to evaluate the separation quality. But I still confuse as that why the results have higher SI-SDRi but with a lower SDRi.

@xixihahaggg @mpariente 
The `get_metrics()` doesn't have the SI-SDRi metric. May I kindly ask how did you compute them?

**Comment by jvel07** [comment]
@xixihahaggg, you mean that if the list goes from this:
`ALL_METRICS = ["si_sdr", "sdr", "sir", "sar", "stoi", "pesq"]`
to this:
`ALL_METRICS = ["si_sdr", "sdr", "sir", "sar", "stoi", "pesq", "si_sdri"]`
where `si_sdri` is the new element in it, asteroid will return such a metric? Meaning it's already implemented?
