### ISSUE TITLE
Installation with conda 

### ISSUE THREAD

**Issue by vic4code** [asteroid-team/asteroid#552]
## ❓ Questions and Help

Hi, I used conda to create environment and install this repo, but I got `ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/requirements/install.txt'`. 

I am not sure if the prefix `file:` on line number 9 in `environment.yml` is necessary. But I removed it and it worked normally.

```
- pip:
    - -r file:requirements.txt

to 

- pip:
    - -r requirements.txt
```

**Comment by mpariente** [comment]
@mcernak, do you want to have a look?

**Comment by mpariente** [comment]
Closing this issue. Feel free to reopen if needed.
