### ISSUE TITLE
Sepformer implementation

### ISSUE THREAD

**Issue by rohitpaturi** [asteroid-team/asteroid#553]
I am trying to use the official Sepformer implementation from SpeechBrain (SepformerWrapper here: https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/lobes/models/dual_path.py) with asteroid as mentioned https://github.com/asteroid-team/asteroid/issues/510 and I see that the loss (neg SI-SDR) is always positive and oscillating around 2dB even after 20 epochs with LibriMix. Anyone encountered this issue with speechbrain sepformer? Any pointers on making Sepformer implementation work will be appreciated.

**Comment by mpariente** [comment]
@popcornell had this in his plans IIRC

Le dim. 12 sept. 2021 à 03:38, rohitpaturi ***@***.***> a
écrit :

**Comment by popcornell** [comment]
Did you simply wrapped speechbrain code with asteroid ? It could be there is something off with the optimizer not optimizing some layers.

**Comment by rohitpaturi** [comment]
My bad, I was able to get it working fine by bootstrapping with the wsjMix pretrained model and turning off the dropout. The loss now goes to -20 within a few epochs. 
So, closing this issue.
