### ISSUE TITLE
RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: ``

### ISSUE THREAD

**Issue by srdfjy** [asteroid-team/asteroid#554]
hi，I run the default DeepClustering recipe and reported this error. What could cause it?

RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: ``

**Comment by mpariente** [comment]
Your version of lightning?

**Comment by srdfjy** [comment]
hi，@mpariente 

pytorch-lightning       1.4.5

**Comment by srdfjy** [comment]
I upgraded to Lightning, but I got the following error again:

ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

**Comment by srdfjy** [comment]
I reduced the batch_size and num_work, but the error at the top appeared again: "RuntimeError: Early stopping conditioned on metric `val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: ``"

pytorch-lightning 1.4.6

**Comment by mpariente** [comment]
Can you try with lightning 1.1.2 please? 

Otherwise, make sure the loss name is present.

**Comment by srdfjy** [comment]
thanks @mpariente
