### ISSUE TITLE
Getting started tutorial fails to import Trainer from pytorch_lightning in Google Colab

### ISSUE THREAD

**Issue by mplanton** [asteroid-team/asteroid#566]
When running the [Getting Started Notebook](https://github.com/asteroid-team/asteroid/blob/master/notebooks/00_GettingStarted.ipynb) in Google Colab, the code

```from pytorch_lightning import Trainer```

produces the error

    ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE

This might be related to an error from installing asteroid with

```!pip install -U asteroid```

which produces the error

    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    torchvision 0.10.0+cu111 requires torch==1.9.0, but you have torch 1.10.0 which is incompatible.
    torchtext 0.10.0 requires torch==1.9.0, but you have torch 1.10.0 which is incompatible.

So the _Train your own model_ code cell cannot be executed.

**Comment by mpariente** [comment]
Closing now. Feel free to reopen if it's still an issue.
