### ISSUE TITLE
Do we have a recipe for AEC?

### ISSUE THREAD

**Issue by poor1017** [asteroid-team/asteroid#605]
Hi

Do we have a recipe for AEC? I think AEC is part speech separation. Now most solutions are DSP solutions. Some reearches of deep learning E2E solution or DSP+DL solution have been developped. Does asteroid have the plan for this?

Thank you!

**Comment by mpariente** [comment]
Having a recipe for AEC would be great ! Do you want to contribute to that?

**Comment by poor1017** [comment]
I am a new asteroid user. Maybe when I have free time, I will have a try.

**Comment by mpariente** [comment]
> I am a new asteroid user.

Anyone is new at some point :wink: We'll guide you to make it right if you put the effort !

**Comment by mpariente** [comment]
Closing this for now. Please re-open if needed.
