### ISSUE TITLE
Cumulative normalization, wrong variance computation

### ISSUE THREAD

**Issue by zmolikova** [asteroid-team/asteroid#648]
Hi,
I suspect that the computation of variance in `CumLN` is missing a division by the length of the sequence. That is:

https://github.com/asteroid-team/asteroid/blob/140733bbaafb5940e1b542c7522d4e3b0ba875bb/asteroid/masknn/norms.py#L101

should be
`cum_var = cum_pow_sum / cnt - cum_mean.pow(2)`
as in $var(x) = E[x^2] - E[x]^2$.

**Comment by mpariente** [comment]
You're fully right, thank you ! 

Could you please submit a PR ?
