### ISSUE TITLE
how to train the dataset

### ISSUE THREAD

**Issue by zhang-chongxiang** [asteroid-team/asteroid#686]
I want to know how to train a dataset with source code, such as training wham with ConvTasNet and evaluating its performance.

**Comment by mpariente** [comment]
Have you checked the recipes (egs)?

**Comment by zhang-chongxiang** [comment]
> Have you checked the recipes (egs)?

I'm sorry I'm a beginner at this. I looked at the contents of egs, but I still don't quite understand the order of execution. For example, in the ConvTasNet directory under wham, I run prepare_data.sh and nothing happens. I know what these scripts do, but I don't know how to execute them. Could you please give me some guidance?

**Comment by mpariente** [comment]
The entry point is `run.sh`. 

Read the docs to get familiar with the organization : https://github.com/asteroid-team/asteroid/tree/master/egs
