### ISSUE TITLE
Transfer learning of pretrained model on custom dataset

### ISSUE THREAD

**Issue by thedragoncoder** [asteroid-team/asteroid#687]
I wanted to use the pretrained model for example <br>`model = BaseModel.from_pretrained("JorisCos/ConvTasNet_Libri3Mix_sepclean_16k")`<br> to train on my custom dataset ( using the concept of transfer learning).<br> 1.  I have used the dataset that looks exactly like libriMix, but I am unsure whether the model is picking up the weights of the pretrained model or if it is assigning the weights randomly.<br> 2.  [https://github.com/asteroid-team/asteroid/blob/master/notebooks/00_GettingStarted.ipynb](url), In the following demo, if I replace the line <br>`model = DPRNNTasNet(n_src=2)`<br> with the line `model = BaseModel.from_pretrained("JorisCos/ConvTasNet_Libri3Mix_sepclean_16k")`, I am getting an error stating the following :
![image](https://github.com/asteroid-team/asteroid/assets/55568211/d4b3edf5-712f-4be1-8b5e-9401253ce312)
<br>Please guide me as to what is the right way of transfer learning, as well as, please provide me an insight as to why there is an error coming up. 

Thank you in advance.

**Comment by thedragoncoder** [comment]
I found out why there was an error in pt2. I twas because the number of sources that was used is 3 in the pretrained model, while I had only two sources.

**Comment by mpariente** [comment]
Thanks for reporting your solution !
